### ISSUE TITLE
proj not building

### ISSUE THREAD

**Issue by ajonno** [thedevme/reactiveuikit-demo#1]
hi there, thanks for the great intro video (via React)
- im using XCode 7.3.1
- **pod install** ran fine:

_The version of CocoaPods used to generate the lockfile (1.0.0) is higher than the version of the current executable (0.39.0). Incompatibility issues may arise.
Downloading dependencies
**Using ReactiveKit (2.1.1)
Using ReactiveUIKit (2.0.1)
Using SwiftyTimer (1.2.0)**
Generating Pods project
Integrating client project
Pod installation complete! There are 3 dependencies from the Podfile and 3 total pods installed.__

building in XCode fails with 3 errors: 
- in ReactiveKitDemo

> ld: framework not found Pods_App_ReactiveKitDemo
- in ReactiveKit / ReactiveKit.h

> Include of non-modular header inside framework module 'ReactiveKit.ReactiveKit'
> 
> Could not build Objective-C module 'ReactiveKit'

**Comment by thedevme** [comment]
Just means in order to use pods you have to update to 1.0 - [sudo] gem install cocoapods should get you to cocoapods 1.0.

**Comment by brewitman** [comment]
I have Xcode 7.3.1 and update of cocoapods is not enough.
Beside that you have to:
In ReactiveKit.h and RKProtocolProxyBase.m
  change `#import <ReactiveKit/RKProtocolProxyBase.h>`
  to `#import "RKProtocolProxyBase.h"`

It is still not enough as I received a linker error saying Pods_App_ReactiveKiDemo.framework can not be found.
Solved by this:
From ReactiveKitDemo/Pods delete
**Pods-App-ReactiveKitDemo.debug.xcconfig
Pods-App-ReactiveKitDemo.release.xcconfig**

From ReactiveKitDemo/Frameworks delete
**Pods_App_ReactiveKitDemo.framework**

Now it works :)

**Comment by thedevme** [comment]
Thanks when he downloaded it pods were in and I removed them after my comment. But I have updated and removed those files from git.  Should be good now. I just downloaded it and did pod install and ran the project.  Sorry shouldn't of included my Podfiles into git.
