### ISSUE TITLE
'invalid virtual filesystem overlay file' error

### ISSUE THREAD

**Issue by MdBee** [thedevme/reactiveuikit-demo#2]
Hi Craig,
Found your talk via Natasha.
I'm getting this build error:

> invalid virtual filesystem overlay file '/Users/matt.d.bearson/Library/Developer/Xcode/DerivedData/Build/Intermediates/Pods.build/Debug-iphonesimulator/ReactiveUIKit.build/unextended-module-overlay.yaml'

Any tips?

thanks,
Matt

**Comment by MdBee** [comment]
Craig, by the way, your talk was terrific.  Thank you for creating it!
I solved this issue by updating my Ruby and my Cocoapods repo.  So nevermind.

**Comment by thedevme** [comment]
Hey no problem and thank you for the kind words I appreciate it.
